[project]
name = "hn-time-capsule"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=2.9.0",
    "python-dotenv>=1.0.0",
    "requests>=2.32.5",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.16",
]
